### ISSUE TITLE
로그인 서비스

### ISSUE THREAD

**Issue by DYShin1** [yeonbong1jo-NaN-Null-Joahae/Member-Management#9]
## 어떤 기능인가요?
 > Password, ID 입력 시 로그인 여부 출력

## 작업 상세 내용

- [x] MemeberRepository 클래스 내 로그인 여부 확인 메소드
- [x] MemberService 클래스에서 검색 데이터 출력
- [x] Application case 6. 만들기

**Comment by bucky1005** [comment]
메소드명 loginCheck로 통일하는거 어떨까요??
